# Generated by Django 2.2 on 2020-05-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0004_auto_20200513_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateProyec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=250, verbose_name='Lenguaje')),
                ('motorBd', models.CharField(max_length=100, verbose_name='Motor BD')),
                ('arqui', models.CharField(max_length=250, verbose_name='arquitectura')),
            ],
            options={
                'verbose_name': 'CateProyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTipoDo', models.CharField(max_length=45, verbose_name='Tipo documento')),
            ],
            options={
                'verbose_name': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPro', models.CharField(max_length=250, verbose_name='Nombre de Proyecto')),
                ('desProyec', models.CharField(max_length=250, verbose_name='Descripción')),
                ('imgPro', models.ImageField(default='proyec.png', upload_to='', verbose_name='Imagen de Proyecto')),
                ('fechaIni', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('fechaFi', models.DateTimeField(verbose_name='Fecha Final')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('estaPro', models.CharField(max_length=100, verbose_name='Estado')),
                ('idCate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CateProyec', verbose_name='Identificador del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdocu', models.CharField(max_length=250, verbose_name='Nombre Documento')),
                ('patDocu', models.CharField(max_length=200, verbose_name='URL git')),
                ('idPro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto', verbose_name='Proyecto')),
                ('idTiDo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Tipo Documento')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documentos ',
            },
        ),
    ]
