# Generated by Django 2.2 on 2020-05-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateproyec',
            options={'verbose_name': 'Categoria Del Proyecto', 'verbose_name_plural': 'Categoria de Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento ', 'verbose_name_plural': 'Documentos '},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Datos del Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tipodocu',
            options={'verbose_name': 'Tipos de documento', 'verbose_name_plural': 'Tipo de documento'},
        ),
    ]
