# Generated by Django 2.2 on 2020-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200514_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imgPro',
            field=models.ImageField(default='proyec.png', upload_to='proyecto/img', verbose_name='Imagen de Proyecto'),
        ),
    ]
