# Generated by Django 2.2 on 2020-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Informacion'},
        ),
        migrations.AlterModelOptions(
            name='detarol',
            options={'verbose_name': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habiluser',
            options={'verbose_name': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Niveles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='habiluser',
            name='descHabil',
            field=models.TextField(max_length=2000, verbose_name='Descripcion de la Habilidad'),
        ),
    ]
