# Generated by Django 2.2 on 2020-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200510_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='adddata',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cargado el'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='apeUser',
            field=models.CharField(max_length=250, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='modifiat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='nomUser',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomres'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='geneUser',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roleNama',
            field=models.CharField(max_length=50, verbose_name='Nombre Rol'),
        ),
    ]
