# Generated by Django 2.2 on 2020-05-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200514_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos de Usuario', 'verbose_name_plural': 'Informacion'},
        ),
        migrations.AlterModelOptions(
            name='detarol',
            options={'verbose_name': 'Roles de Usuario', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habiluser',
            options={'verbose_name': 'Habilidades del Usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de Habilidades', 'verbose_name_plural': 'Niveles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
